name: Makefile CI

on:
  push:
    branches: [ "master", "dermatest" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install reuirements
      run: |
        sudo apt-get install -y python3 python3-pip
        sudo pip3 install -r requirements.txt
        sudo pip3 install -r requirements-dev.txt
        sudo pip3 install -r requirements-test.txt

    - name: Build and install package
      run: |
        make build
        make install

    - name: Run tests
      run: make test

    - name: Build wheel
      run: make wheel
